// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFMy3_Ww-s6GxEETTtM1rxteqJbSU7-T4',
    appId: '1:524725198588:web:f4a25838c8edbb5f020179',
    messagingSenderId: '524725198588',
    projectId: 'expense-tracker-48ad6',
    authDomain: 'expense-tracker-48ad6.firebaseapp.com',
    storageBucket: 'expense-tracker-48ad6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Uje8-LyPXnauaf5wF-8IHEZtpogED94',
    appId: '1:524725198588:android:e091899e6c7835ac020179',
    messagingSenderId: '524725198588',
    projectId: 'expense-tracker-48ad6',
    storageBucket: 'expense-tracker-48ad6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChAmP9-2zZ7O4NxOoHrHkI1F823KRbevA',
    appId: '1:524725198588:ios:d1b892339ebe94f8020179',
    messagingSenderId: '524725198588',
    projectId: 'expense-tracker-48ad6',
    storageBucket: 'expense-tracker-48ad6.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChAmP9-2zZ7O4NxOoHrHkI1F823KRbevA',
    appId: '1:524725198588:ios:d1b892339ebe94f8020179',
    messagingSenderId: '524725198588',
    projectId: 'expense-tracker-48ad6',
    storageBucket: 'expense-tracker-48ad6.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFMy3_Ww-s6GxEETTtM1rxteqJbSU7-T4',
    appId: '1:524725198588:web:f926e6aad2f7a64b020179',
    messagingSenderId: '524725198588',
    projectId: 'expense-tracker-48ad6',
    authDomain: 'expense-tracker-48ad6.firebaseapp.com',
    storageBucket: 'expense-tracker-48ad6.firebasestorage.app',
  );
}
